### ISSUE TITLE
Even though addon localization is included in NVDA's translation system, the addon doesn't contain localizations

### ISSUE THREAD

**Issue by burakyuksek** [ogomez92/winWizard#7]
I am the Turkish translator of this addon. I have translated all the strings but the addon doesn't pull localizations from the NVDA server so the translation is pretty much for nothing. Can you please make it so the addon pulls the translations?
The translations do work if copied to the locales directory manually.

**Comment by lukaszgo1** [comment]
@burakyuksek  Translations which are present  in the translations system would be included in the new version which I'm going to release in the coming days. Just FYI: the new version contains some new strings so if you would like to have a completely uptodate Turkish translation you may want to monitor new strings on Assembla after the next synchronization.

**Comment by lukaszgo1** [comment]
The new version, released about 5 minutes ago, contains all translations submitted until last Friday. I'm going to close this issue since even though the Turkish translation included in the add-on does not cover all translatable strings, no new translations were included in SVN.

**Comment by burakyuksek** [comment]
Oh well, I forgot to translate. Doing it now, hopefully it can be included in the next version.
